### PR TITLE
:sparkles: dynamic routes (code-splitting)

### PR DESCRIPTION
**Pull request by bpetetot**
## Purpose
Use of dynamic imports of component and loading component only when the route is matching.
It works very well with code splitting.

## Use
```js
forRoute('MY_ROUTE', { dynamic: true })(() => import('./myComp.jsx'))

// or

forRoute.dynamic('MY_ROUTE')(() => import('./myComp.jsx'))
```

## Todo
- [X]  develop feature
- [ ]  tests
- [ ]  documentation

### CODE REVIEW

**Comment by bpetetot** [comment]
@fabienjuif what do you think about this feature ?
It would be great for conference hall (splitting speaker hall and organizer hall components)

**Comment by fabienjuif** [comment]
It seems very nice but it doesn't work well with other options as you show it.
I speak about dynamic/absolute right now.

I would be a great addition (this little issue aside).

**Comment by bpetetot** [comment]
I think about this PR and it seems that's not the good lib where we have to add code splitting, because I can't set a loading indicator while the route is loading. I think the best place to manage code splitting is in `hoc-react-loader` 
So I could do something like that and manage my loading indicator with `hoc-react-loader` : 
```js
compose(
  forRoute.absolute('MY_ROUTE'),
  myHocReactLoader,
)(() => import('./myComp.jsx'))
```

This is my use case today, but if someone doesn't need to have a loading indicator or doesn't use `hoc-react-loader` we can also manage dynamic imports in `hoc-little-router`

What do you think about that ?

**Comment by fabienjuif** [comment]
Maybe we should add a new hoc and compose as we want to.

```
compose(
  // what
  // I
  // want
  lazyLoader,
)(() => import ('./myComp.jsx'))
```

**Comment by fabienjuif** [comment]
inactive

**Pull request closed without merging**
